MVP - Note-Taking & Favourites
sh1ggy/ddr-md pull request #6
Opened 2024-05-31 14:51 UTC by sh1ggy

This PR covers the following: 
- Installation of the `sqfite` package
- Introduction of the `DatabaseProvider` static class to obfuscate the business logic for the local DB
- Restructure of the difficulty folder page & song list folder page. 

This PR relates to the following Trello tasks:
- [SqLite Storage for note-taking](https://trello.com/c/x9dgkiKA/27-sqlite-storage-for-notetaking)
- [Marking songs as favourites](https://trello.com/c/0E3Y2NrF/38-marking-songs-as-favourites-sqlite)

[PR #5](https://github.com/sh1ggy/ddr-md/pull/5) should be performed before this one.

2024-05-31 15:28 UTC, ProPablo requested changes

2024-05-31 15:55 UTC, Ariit0 requested changes

2024-06-03 13:55 UTC, ProPablo approved these changes
deez

2024-06-04 10:16 UTC, Ariit0 approved these changes
🚀

2024-06-05 01:38 UTC, merged